import "../globals.css"

export const metadata = {
  title: 'Symphonize, Inc - Please SignIn',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className="content flex flex-row flex-wrap">
          <aside className="w-0 sm:w-2/3  bg-no-repeat bg-cover bg-center bg-[url('/craft-hero.jpg')]">
          </aside>
          <main className="flex-grow pt-1 p-2 bg-white">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
